steps:
- name: "gcr.io/cloud-builders/gcloud"
  id: "Decrypt Environment Variables"
  args:
    [
    "kms",
    "decrypt",
    "--key=envvars",
    "--keyring=global",
    "--location=global",
    "--ciphertext-file=envvars.encrypted",
    "--plaintext-file=envvars.yaml"
    ]
  timeout: 60s
- name: "gcr.io/cloud-builders/gcloud"
  id: "Deploy Cloud Function"
  waitFor:
    [
    "Decrypt Environment Variables"
    ]
  args:
    [
    "functions",
    "deploy",
    "sendgrid-function",
    "--region=us-central1",
    "--entry-point=sendgrid_function",
    "--memory=128MB",
    "--runtime=python37",
    "--timeout=30s",
    "--max-instances=1",
    "--trigger-http",
    "--env-vars-file=envvars.yaml"
    ]
  timeout: 120s
timeout: 180s
