name: Python Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Python Linting
    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@master
  style:
    runs-on: ubuntu-latest
    name: Python Style Checking
    steps:
      - uses: andymckay/pycodestyle-action@master
  security:
    runs-on: ubuntu-latest
    name: Snyk Security Scan
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
