name: Python Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Python Linting
    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@master
  check:
    runs-on: ubuntu-latest
    name: Python Style Checking
    steps:  
      - uses: andymckay/pycodestyle-action@0.1.3
