name: Python Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@master
  style:
    runs-on: ubuntu-latest
    name: Style Checking
    steps:  
      - uses: andymckay/pycodestyle-action@0.1.3
  secrets:
    runs-on: ubuntu-latest
    name: Secret Scan
    steps:  
      - uses: max/secret-scan@master
